### PR TITLE
add fahrenheit2Celcius functions

### PR DESCRIPTION
**Pull request by guillemontecinos**

### CODE REVIEW

**Comment by guillemontecinos** [comment]
I didn't sync my local repo with the upstream before doing this, so I'll close this PR and do it again.

**Comment by shiffman** [comment]
No worries! (in theory you can update the pull request here (?) but either way is great.)

**Comment by guillemontecinos** [comment]
You're totally right. I re-opened the PR and solved merge conflicts in my local fork and. Now I'm waiting for the checks -which should fail. Thanks!

**Comment by guillemontecinos** [comment]
@shiffman how long should I expected for checks to be completed?

**Comment by shiffman** [comment]
I think something is broken, it shouldn't take this long! I'll look into it. . .

**Comment by guillemontecinos** [comment]
thanks!

**Comment by guillemontecinos** [comment]
Is this be useful? [https://circleci.com/docs/2.0/workflows-waiting-status/](url)

**Comment by shiffman** [comment]
I got it building again and tried to merge stuff but now it's failing! Feel free to take a look and try to make any changes?

**Comment by shiffman** [comment]
The function got 12! Oops?

screen shot 2018-10-01 at 5 58 20 pm

**Comment by guillemontecinos** [comment]
> The function got 12! Oops?
> 
> screen shot 2018-10-01 at 5 58 20 pm

So, the original plan was to commit a function that was misdefined in order to trigger error in checks and then fix it.

**Comment by shiffman** [comment]
Oh awesome, yes, it worked! 😄

**Pull request merged**
